worshop-project/src/Domain/Category.java
worshop-project/src/Domain/Item.java

-added category Enum
-implemented getters and setters for item fields
-implemented update rating
-implemented buy item
to do:
-decide how to address the ID of product
-synchronization

basic implementation

---

worshop-project/src/Domain/Shop.java

shop basic getters and setters

basic impl: constructer,getters and setters

---

worshop-project/src/Domain/Item.java
worshop-project/src/Tests/item_test.java

שינוי קטן במחלקה item 
שם משמעותי לפרמטר בפונקציה updateRating

updateRating fix

---

worshop-project/src/Tests/ItemTest.java
worshop-project/src/Tests/item_test.java

30 item tests

---

worshop-project/src/Domain/Founder.java
worshop-project/src/Domain/Owner.java

זה ממומש בהתאם לעדכון הסופי של IRole

add owner and founder

---

worshop-project/src/Domain/Manager.java
worshop-project/src/Domain/Owner.java
worshop-project/src/Domain/Permission.java
worshop-project/src/Tests/ManagerTest.java

הוספתי כמה הרשאות למנהל חנות שעלו מהקובץ דרישות.
בינתיים עשיתי הדפסות ולא זריקת שגיאות במתודות ללא מימוש כדי שבהרצת use case לא יהיה בעיות. התכנון הוא לשנות אותם מהדפסה ברגע שיהיה תמונה יותר ברורה

add test and some changes

---

worshop-project/src/Tests/OwnerTest.java
worshop-project/src/Tests/RegisteredTests.java

שמנו בהערה את כל הטסטים עם השגיאות שרלוונטיות לי וללביא

test for later

---

worshop-project/src/Domain/DTOs/UserDTO.java
worshop-project/src/Domain/DTOs/UserRoleDTO.java
worshop-project/src/Domain/Repositories/IUserRepository.java

UserDTO + UserRoleDTO(for shopID:IRole table) + extra methods in the ……repository
הוספתי מחלקות פשוטות שיעזרו לי לנהל את המידע לגבי המשתמש בUserService

Add UserDTO

---

worshop-project/src/Domain/ShoppingBasket.java
worshop-project/src/Domain/ShoppingCart.java

Fixed basket issue.

---

worshop-project/src/Domain/Guest.java
worshop-project/src/Domain/Registered.java
worshop-project/src/Tests/GuestTest.java

שינוי למחלקות שעכשיו תהינה מעודכנות עם הלוגיקה של הסרוויס

Fixed guest and registered for updated logic + tests run

---

worshop-project/src/Domain/DomainServices/PurchaseService.java

updated PurchaseService

---

worshop-project/src/Domain/DomainServices/PurchaseService.java
worshop-project/src/Domain/ShoppingCart.java

Done with PurchaseService.

---

worshop-project/src/Domain/DTOs/CartShopItemDTO.java
worshop-project/src/Domain/DTOs/UserDTO.java
worshop-project/src/Domain/DTOs/UserRoleDTO.java
worshop-project/src/Domain/DTOs/UserShopPermissionDTO.java
worshop-project/src/Domain/DTOs/UserShopRoleDTO.java
worshop-project/src/Domain/Guest.java
worshop-project/src/Domain/IRole.java
worshop-project/src/Domain/Manager.java
worshop-project/src/Domain/Owner.java
worshop-project/src/Domain/Permission.java
worshop-project/src/Domain/Registered.java
worshop-project/src/Domain/Repositories/IUserRepository.java
worshop-project/src/Domain/Repositories/MemoryUserRepository.java
worshop-project/src/Service/UserService.java
worshop-project/src/Tests/GuestTest.java
worshop-project/src/Tests/RegisteredTest.java

סיימנו userrepository.
בנוסף, נראה שסיימנו גם userservice, פשוט אנחנו צריכים מימושים של כמה דברים בpurchaseservice

99 userrep fix

---

workshop-project/src/main/Domain/DTOs/ItemDTO.java
workshop-project/src/main/Domain/DomainServices/ManagementService.java
workshop-project/src/main/Domain/DomainServices/PurchaseService.java
workshop-project/src/main/Domain/Item.java
workshop-project/src/main/Domain/Permission.java
workshop-project/src/main/Domain/Purchase/BidPurchase.java
workshop-project/src/main/Domain/Purchase/PurchasePolicy.java
workshop-project/src/main/Domain/Shop.java
workshop-project/src/main/Service/ShopService.java
workshop-project/src/main/Service/UserService.java

-answer bid
-counter bid
-purchaseType
-item description

129 acceptreject bid offer use case

---

.idea/compiler.xml
.idea/modules.xml
workshop-project/src/main/Domain/DTOs/Order.java
workshop-project/src/main/Domain/DomainServices/PurchaseService.java

changed in order from username to userID

fixing purchaseService and order

---

workshop-project/src/Tests/Tests/endToEndTest_1.java
workshop-project/src/main/Service/UserService.java

Added the item addition test and the management test. We are done with the first one and almost with the second one.

Added 2 end to end tests; finished with one of them

---

workshop-project/src/Tests/Tests/endToEndTest_1.java
workshop-project/src/main/Service/OrderService.java
workshop-project/src/main/Service/UserService.java

-from now user service doesnt need order Rep

cartService became OrderService

---

workshop-project/src/main/Domain/Repositories/MemoryOrderRepository.java
workshop-project/src/main/Domain/Repositories/MemoryShopRepository.java
workshop-project/src/main/Domain/Repositories/MemoryUserRepository.java

all repos throw exceptions in case the relevant object is not found

added exceptions

---

workshop-project/src/Tests/Tests/AccepanceTests.java
workshop-project/src/main/Domain/Purchase/BidPurchase.java
workshop-project/src/main/Service/OrderService.java

Fixed empty cart tests + Checking invariant in unsuccessfulpurchase + bid tests + fixing concurrency tests

Finished Tests - without auction

---

.idea/.copilot-plugin
workshop-project/src/main/frontend/generated/vaadin.ts
workshop-project/src/main/java/com/halilovindustries/backend/Domain/DTOs/NotificationDTO.java
workshop-project/src/main/java/com/halilovindustries/backend/Infrastructure/DbNotificationRepository.java
workshop-project/src/main/java/com/halilovindustries/backend/Infrastructure/JpaNotificationRepository.java

Add NotificationDTO entity and JPA repos

Added NotificationDTO entity and JPA repository implementations
